language: groovy
jdk:
- oraclejdk7
sudo: false
branches:
  only:
  - master
before_install:
 - wget -q https://raw.githubusercontent.com/AtlasOfLivingAustralia/travis-build-configuration/master/ala_common.sh
 - chmod +x ala_common.sh
 - source ./ala_common.sh
 - ala_travis_grails_setup_env
script:
 - ala_travis_grails_build
env:
  global:
  - secure: fwa7jtwNL/MNa3+iI+r0jrGwnQcC8fYtgH9vbOT3x9MHo0b2K2CCTq+io+U2iDhFpDt1Tee49ZqL38aQV+/Q7oW9OddRCBhpPafLwvIeAeEAzYVfZzYj0M5QfomqhQfFqaeBlsDGWLmfqs+Qa56acG/5AXvy2bdIBkx8eobxKHw=
  - secure: JICocWnUXHHv+yt1XM/8GcurEmaNwzAbnmAGylaVriCq98m31clDGms1OKoHU11g9Ux8uNSmydafvf+oEFzpm8LAyqrtDcPBqi8UXG+4AY3SctutdDGHE2Ue3ly8HlVkMY2e9wnA2bU/Wmq4VesyvPCIRp/IeGi+sE02F+3IYAQ=
