---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.biocache.hubs

    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache.xml'
            lockTimeout: 200 # In milliseconds

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**

security:
    cas:
        casServerName: 'https://auth.ala.org.au'
        uriFilterPattern: '/alaAdmin,/alaAdmin.*'
        uriExclusionFilterPattern: '/portal/q.*,/portal/messages.*,/portal/sessionCache.*,/static.*,/assets.*'
        authenticateOnlyIfLoggedInPattern: '/portal.*,/,/portal/config.*,/portal/i18n.*,/hub/[a-zA-Z0-9]+'
        loginUrl: 'https://auth.ala.org.au/cas/login'
        logoutUrl: 'https://auth.ala.org.au/cas/logout'
        gateway: false
        casServerUrlPrefix: 'https://auth.ala.org.au/cas'
        bypass: false # set to true for non-ALA deployment
        disableCAS: false
        roleAttribute: authority
        ignoreCase: true
        authCookieName: ALA-Auth

environments:
    development:
        security:
            cas:
                appServerName: "http://devt.ala.org.au:8081"
        server:
            port: 8081
            use-forward-headers: true
        grails:
            serverURL: "http://devt.ala.org.au:8081"