---
dwc:
    exclude: 'dataHubUid,dataProviderUid,institutionUid,year,month,day,modified,left,right,provenance,taxonID,preferredFlag,outlierForLayers,speciesGroups,associatedMedia,images,userQualityAssertion,speciesHabitats,duplicationType,taxonomicIssues,subspeciesID,nameMatchMetric,sounds,datasetName, fieldNumber, samplingProtocol'

grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.biocache.hubs

    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache.xml'
            lockTimeout: 200 # In milliseconds

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

spring:
    devtools:
        restart:
            exclude:
                - grails-app/views/**
                - grails-app/i18n/**
                - grails-app/conf/**


security:
    cas:
        enabled: false # default is true, undefined behaviour if this omitted
    oidc:
        enabled: true # default is false
        discoveryUri: 'https://auth-test.ala.org.au/cas/oidc/.well-known'
        clientId: 'change me'
        secret: 'change me'
        scope: 'openid,profile,email,ala,roles'

webservice:
    jwt: true

environments:
    development:
        security:
            cas:
                appServerName: "http://devt.ala.org.au:8081"
        server:
            port: 8081
            use-forward-headers: true
        grails:
            serverURL: "http://devt.ala.org.au:8081"