---
dwc:
    exclude: 'dataHubUid,dataProviderUid,institutionUid,year,month,day,modified,left,right,provenance,taxonID,preferredFlag,outlierForLayers,speciesGroups,associatedMedia,images,userQualityAssertion,speciesHabitats,duplicationType,taxonomicIssues,subspeciesID,nameMatchMetric,sounds,datasetName, fieldNumber, samplingProtocol'

grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.biocache.hubs

    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache.xml'
            lockTimeout: 200 # In milliseconds

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

