---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: au.org.ala.biocache.hubs

    cache:
        ehcache:
            ehcacheXmlLocation: 'classpath:ehcache.xml'
            lockTimeout: 200 # In milliseconds

info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'

hibernate:
    dialect: org.hibernate.dialect.H2Dialect
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

database:
    directory: /data/ala-hub/database

dataSource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:${database.directory}
    dbCreate: validate
    pooled: true
    jmxExport: true
